# -*- coding: utf-8 -*-
"""app.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/125XH3HIRgigl_mR2bsJOV0bSUDM0QIBI
"""

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
from pywebio import start_server
from pywebio.input import file_upload, select
from pywebio.output import *
from pywebio.session import run_async
import io
import base64
from datetime import datetime

class BankTransactionApp:
    def __init__(self):
        self.db_path = "bank_transaction.db"
        self.initialize_database()

    def initialize_database(self):
        """Initialize the SQLite database"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('''CREATE TABLE IF NOT EXISTS transactions (
            TransactionID TEXT PRIMARY KEY,
            CustomerID TEXT,
            CustomerDOB TEXT,
            CustGender TEXT,
            CustLocation TEXT,
            CustAccountBalance REAL,
            TransactionDate TEXT,
            TransactionTime INTEGER,
            TransactionAmount REAL)''')
        conn.commit()
        conn.close()

    def upload_file(self):
        """Handle file upload and display preview"""
        file = file_upload("Upload Bank Transactions CSV", accept=".csv")
        if not file:
            return

        try:
            # Read and process file
            df = pd.read_csv(io.BytesIO(file['content']))
            df.columns = [col.strip() for col in df.columns]

            # Standardize column names
            column_mapping = {
                'TransactionAmount (INR)': 'TransactionAmount',
                'TransactionTime (LocalTime)': 'TransactionTime',
                'Customer Account Balance': 'CustAccountBalance'
            }
            df.rename(columns=column_mapping, inplace=True)

            # Save to database
            conn = sqlite3.connect(self.db_path)
            df.to_sql("transactions", conn, if_exists="replace", index=False)
            conn.close()

            put_success("Transaction data uploaded successfully!")
            with use_scope('upload-content', clear=True):
                put_table(df.head(10).to_dict('records'))
        except Exception as e:
            toast(f"Error: {str(e)}", color='error')

    def get_data_from_db(self, query):
        """Execute SQL query and return DataFrame"""
        conn = sqlite3.connect(self.db_path)
        df = pd.read_sql_query(query, conn)
        conn.close()
        return df

    def transaction_analysis(self):
        """Show transaction amount analysis"""
        with use_scope('transaction-analysis', clear=True):
            put_markdown("## Transaction Amount Analysis")

            analysis_type = select("Select analysis type", [
                'Top 10 Transactions',
                'Transaction Amount Distribution',
                'Daily Transaction Trends',
                'Transaction Amount by Location'
            ])

            if analysis_type == 'Top 10 Transactions':
                df = self.get_data_from_db("""
                    SELECT * FROM transactions
                    ORDER BY TransactionAmount DESC
                    LIMIT 10""")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.barplot(x='TransactionID', y='TransactionAmount',
                           data=df, palette='viridis', ax=ax)
                ax.set_title('Top 10 Transactions by Amount')
                ax.set_ylabel('Amount (₹)')
                ax.set_xlabel('Transaction ID')
                plt.xticks(rotation=45)
                self.display_plot(fig)
                put_table(df.to_dict('records'))

            elif analysis_type == 'Transaction Amount Distribution':
                df = self.get_data_from_db("SELECT TransactionAmount FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.histplot(df['TransactionAmount'], bins=20, kde=True, ax=ax)
                ax.set_title('Transaction Amount Distribution')
                ax.set_xlabel('Amount (₹)')
                ax.set_ylabel('Number of Transactions')
                self.display_plot(fig)

            elif analysis_type == 'Daily Transaction Trends':
                df = self.get_data_from_db("SELECT TransactionDate, TransactionAmount FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                df['TransactionDate'] = pd.to_datetime(df['TransactionDate'])
                daily_df = df.groupby('TransactionDate')['TransactionAmount'].sum().reset_index()

                fig, ax = plt.subplots(figsize=(12, 6))
                sns.lineplot(x='TransactionDate', y='TransactionAmount',
                            data=daily_df, marker='o', ax=ax)
                ax.set_title('Daily Transaction Amount Trends')
                ax.set_xlabel('Date')
                ax.set_ylabel('Total Amount (₹)')
                plt.xticks(rotation=45)
                self.display_plot(fig)
                put_table(daily_df.to_dict('records'))

            elif analysis_type == 'Transaction Amount by Location':
                df = self.get_data_from_db("""
                    SELECT CustLocation, AVG(TransactionAmount) as AvgAmount,
                    COUNT(*) as TransactionCount
                    FROM transactions
                    GROUP BY CustLocation""")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

                # Average transaction by location
                sns.barplot(x='CustLocation', y='AvgAmount',
                           data=df.sort_values('AvgAmount', ascending=False),
                           palette='coolwarm', ax=ax1)
                ax1.set_title('Average Transaction Amount by Location')
                ax1.set_ylabel('Average Amount (₹)')
                ax1.set_xlabel('Location')
                plt.sca(ax1)
                plt.xticks(rotation=45)

                # Transaction count by location
                sns.barplot(x='CustLocation', y='TransactionCount',
                           data=df.sort_values('TransactionCount', ascending=False),
                           palette='viridis', ax=ax2)
                ax2.set_title('Transaction Count by Location')
                ax2.set_ylabel('Number of Transactions')
                ax2.set_xlabel('Location')
                plt.sca(ax2)
                plt.xticks(rotation=45)

                plt.tight_layout()
                self.display_plot(fig)
                put_table(df.to_dict('records'))

    def customer_analysis(self):
        """Analyze customer behavior"""
        with use_scope('customer-analysis', clear=True):
            put_markdown("## Customer Behavior Analysis")

            analysis_type = select("Select analysis type", [
                'Top Customers by Transaction Volume',
                'Customer Age Analysis',
                'Gender-Based Analysis',
                'Account Balance Distribution'
            ])

            if analysis_type == 'Top Customers by Transaction Volume':
                df = self.get_data_from_db("""
                    SELECT CustomerID, COUNT(*) as TransactionCount,
                    SUM(TransactionAmount) as TotalAmount
                    FROM transactions
                    GROUP BY CustomerID
                    ORDER BY TotalAmount DESC
                    LIMIT 10""")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

                # Total amount by customer
                sns.barplot(x='CustomerID', y='TotalAmount',
                           data=df, palette='magma', ax=ax1)
                ax1.set_title('Total Transaction Amount by Customer')
                ax1.set_ylabel('Total Amount (₹)')
                ax1.set_xlabel('Customer ID')
                plt.sca(ax1)
                plt.xticks(rotation=45)

                # Transaction count by customer
                sns.barplot(x='CustomerID', y='TransactionCount',
                           data=df, palette='plasma', ax=ax2)
                ax2.set_title('Transaction Count by Customer')
                ax2.set_ylabel('Number of Transactions')
                ax2.set_xlabel('Customer ID')
                plt.sca(ax2)
                plt.xticks(rotation=45)

                plt.tight_layout()
                self.display_plot(fig)
                put_table(df.to_dict('records'))

            elif analysis_type == 'Customer Age Analysis':
                df = self.get_data_from_db("SELECT CustomerDOB FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                # Calculate age
                df['CustomerDOB'] = pd.to_datetime(df['CustomerDOB'])
                current_year = datetime.now().year
                df['Age'] = current_year - df['CustomerDOB'].dt.year

                # Categorize into age groups
                bins = [0, 18, 25, 35, 50, 65, 100]
                labels = ['<18', '18-24', '25-34', '35-49', '50-64', '65+']
                df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)

                age_counts = df['AgeGroup'].value_counts().sort_index().reset_index()
                age_counts.columns = ['AgeGroup', 'Count']

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.barplot(x='AgeGroup', y='Count', data=age_counts,
                            palette='coolwarm', ax=ax)
                ax.set_title('Customer Distribution by Age Group')
                ax.set_xlabel('Age Group')
                ax.set_ylabel('Number of Customers')
                self.display_plot(fig)
                put_table(age_counts.to_dict('records'))

            elif analysis_type == 'Gender-Based Analysis':
                df = self.get_data_from_db("""
                    SELECT CustGender,
                    AVG(TransactionAmount) as AvgAmount,
                    COUNT(*) as TransactionCount,
                    AVG(CustAccountBalance) as AvgBalance
                    FROM transactions
                    GROUP BY CustGender""")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

                # Average transaction amount by gender
                sns.barplot(x='CustGender', y='AvgAmount',
                           data=df, palette='viridis', ax=ax1)
                ax1.set_title('Average Transaction Amount by Gender')
                ax1.set_ylabel('Average Amount (₹)')
                ax1.set_xlabel('Gender')

                # Average account balance by gender
                sns.barplot(x='CustGender', y='AvgBalance',
                           data=df, palette='plasma', ax=ax2)
                ax2.set_title('Average Account Balance by Gender')
                ax2.set_ylabel('Average Balance (₹)')
                ax2.set_xlabel('Gender')

                plt.tight_layout()
                self.display_plot(fig)
                put_table(df.to_dict('records'))

            elif analysis_type == 'Account Balance Distribution':
                df = self.get_data_from_db("SELECT CustAccountBalance FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.histplot(df['CustAccountBalance'], bins=20, kde=True, ax=ax)
                ax.set_title('Customer Account Balance Distribution')
                ax.set_xlabel('Account Balance (₹)')
                ax.set_ylabel('Number of Customers')
                self.display_plot(fig)

    def time_analysis(self):
        """Analyze transaction patterns by time"""
        with use_scope('time-analysis', clear=True):
            put_markdown("## Transaction Time Analysis")

            analysis_type = select("Select analysis type", [
                'Hourly Transaction Patterns',
                'Weekday vs Weekend Analysis',
                'Transaction Time Distribution',
                'Time vs Amount Correlation'
            ])

            if analysis_type == 'Hourly Transaction Patterns':
                df = self.get_data_from_db("SELECT TransactionTime FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                # Convert timestamp to hours
                df['Hour'] = pd.to_datetime(df['TransactionTime'], unit='s').dt.hour
                hourly_counts = df['Hour'].value_counts().sort_index().reset_index()
                hourly_counts.columns = ['Hour', 'Count']

                fig, ax = plt.subplots(figsize=(12, 6))
                sns.lineplot(x='Hour', y='Count', data=hourly_counts,
                             marker='o', ax=ax)
                ax.set_title('Transaction Count by Hour of Day')
                ax.set_xlabel('Hour of Day (24-hour format)')
                ax.set_ylabel('Number of Transactions')
                ax.set_xticks(range(0, 24))
                self.display_plot(fig)
                put_table(hourly_counts.to_dict('records'))

            elif analysis_type == 'Weekday vs Weekend Analysis':
                df = self.get_data_from_db("SELECT TransactionDate FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                df['TransactionDate'] = pd.to_datetime(df['TransactionDate'])
                df['DayOfWeek'] = df['TransactionDate'].dt.day_name()
                df['IsWeekend'] = df['TransactionDate'].dt.dayofweek >= 5

                weekday_df = df.groupby('IsWeekend').size().reset_index()
                weekday_df.columns = ['IsWeekend', 'Count']
                weekday_df['IsWeekend'] = weekday_df['IsWeekend'].map({True: 'Weekend', False: 'Weekday'})

                fig, ax = plt.subplots(figsize=(8, 6))
                sns.barplot(x='IsWeekend', y='Count', data=weekday_df,
                           palette='coolwarm', ax=ax)
                ax.set_title('Weekday vs Weekend Transactions')
                ax.set_xlabel('')
                ax.set_ylabel('Number of Transactions')
                self.display_plot(fig)
                put_table(weekday_df.to_dict('records'))

            elif analysis_type == 'Transaction Time Distribution':
                df = self.get_data_from_db("SELECT TransactionTime FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                df['Hour'] = pd.to_datetime(df['TransactionTime'], unit='s').dt.hour

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.histplot(df['Hour'], bins=24, kde=True, ax=ax)
                ax.set_title('Transaction Time Distribution')
                ax.set_xlabel('Hour of Day')
                ax.set_ylabel('Number of Transactions')
                ax.set_xticks(range(0, 24))
                self.display_plot(fig)

            elif analysis_type == 'Time vs Amount Correlation':
                df = self.get_data_from_db("SELECT TransactionTime, TransactionAmount FROM transactions")

                if df.empty:
                    toast("No data available", color='error')
                    return

                df['Hour'] = pd.to_datetime(df['TransactionTime'], unit='s').dt.hour

                fig, ax = plt.subplots(figsize=(10, 6))
                sns.scatterplot(x='Hour', y='TransactionAmount',
                               data=df, alpha=0.6, ax=ax)
                ax.set_title('Transaction Amount by Time of Day')
                ax.set_xlabel('Hour of Day')
                ax.set_ylabel('Transaction Amount (₹)')
                ax.set_xticks(range(0, 24))
                self.display_plot(fig)

    def display_plot(self, fig):
        """Display matplotlib figure as image"""
        img = io.BytesIO()
        plt.savefig(img, format='png', bbox_inches='tight', dpi=100)
        img.seek(0)
        img_data = base64.b64encode(img.read()).decode('utf-8')
        plt.close(fig)
        put_image(f'data:image/png;base64,{img_data}')

    def main(self):
        """Main application interface"""
        put_markdown("# 💰 Bank Transaction Analyzer")

        put_tabs([
            {'title': '📤 Upload Data', 'content': [
                put_button("Upload Transaction Data", onclick=self.upload_file),
                put_scope('upload-content')
            ]},
            {'title': '💸 Transaction Analysis', 'content': [
                put_button("Analyze Transactions", onclick=self.transaction_analysis),
                put_scope('transaction-analysis')
            ]},
            {'title': '👤 Customer Analysis', 'content': [
                put_button("Analyze Customer Behavior", onclick=self.customer_analysis),
                put_scope('customer-analysis')
            ]},
            {'title': '⏰ Time Analysis', 'content': [
                put_button("Analyze Transaction Timing", onclick=self.time_analysis),
                put_scope('time-analysis')
            ]}
        ])

def main():
    app = BankTransactionApp()
    app.main()

if __name__ == '__main__':
    # Start the web server on port 8081
    start_server(main, port=8088, debug=True)

